# An example of ClusterConfig object with highly available NAT gateways
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gmmo-nonprod
  region: ap-southeast-1

vpc:
  nat:
    gateway: Single # other options: Disable, Single, HighlyAvailable (default)

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
